### ISSUE TITLE
Issue loading packages

### ISSUE THREAD

**Issue by ekmcintyre** [DS4PS/cpp-526-fall-2020#8]
At first I could not install.packages because I didn't have Rtools installed. I followed the link and instructions to install it and reopened the Lab 02 template to install.packages. This time it worked but now there is an error in loading the required libraries.

I get this error window:
![image](https://user-images.githubusercontent.com/66448475/91900350-6807be00-ec53-11ea-95af-2f119b3006df.png)

And then an error message in the console:
Error: package or namespace load failed for ‘geojsonio’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/ekmci/Documents/R/win-library/4.0/Rcpp/libs/x64/Rcpp.dll':
  LoadLibrary failure:  The specified procedure could not be found.

**Comment by jamisoncrawford** [comment]
Hi @ekmcintyre, you should never include `install.packages()` in a code chunk unless the chunk options include `eval = FALSE`.

You only need to load the packages with `library()` in a code chunk - typically at the beginning.

If you want to ensure that the packages are installed, you can simply install them in the console or in a separate `.R` script.

Let me know if this helps!

**Comment by ekmcintyre** [comment]
It keeps popping up this error
![image](https://user-images.githubusercontent.com/66448475/91908666-c8e9c300-ec60-11ea-9063-e70b374d2051.png)

And then the same error message at the bottom of this image
![image](https://user-images.githubusercontent.com/66448475/91908718-ddc65680-ec60-11ea-87ee-1b5a999113b6.png)

I checked the install of the packages in the console and that is seen in all of the output in the rest of the image.

**Comment by jacobtnyoung** [comment]
Did you close RStudio and then try:

```
library(geojsonio)
```

If you get the same error, you should close the application and try reinstalling the package.

**Comment by jamisoncrawford** [comment]
@ekmcintyre according to the messages it seems to be installing, but `library()` isn't loading it.  I think @jacobtnyoung is on the right track here.  Try the following, in this order, and test to see if it works in between each:

* Restart the R session (in the top menu, there's "Session" > "New")
* Uninstall the package with `remove.packages()` and reinstall with `install.packages()`
* Delete the file containing the package in this path: `"C:\Users\ekmi\AppData\Local\Temp\RtmpSorqFc\dowloaded_packages"`.

**Comment by ekmcintyre** [comment]
I started a new session and tried to simply run the code chunk to load the required libraries and an error message about geojsonio shows up again. Then I tried to remove and install the package in the console and Rstudio says it couldn't find the object. 
![image](https://user-images.githubusercontent.com/66448475/91921228-d5314880-ec7f-11ea-80c9-45084b1ccf5a.png)

I am also trying to go into my computer and get to that file, but I can't find the AppData folder in my user folder for some reason.

**Comment by ekmcintyre** [comment]
Got to the AppData folders and couldn't find the RtmpSorqFc file

![image](https://user-images.githubusercontent.com/66448475/91921576-ad8eb000-ec80-11ea-96f5-3beefe401819.png)

**Comment by ekmcintyre** [comment]
Figured out I was missing the quotations. Reinstalled the package and can find the file on my computer. When R goes to run the code chunk for loading the libraries provided in the template, it seems to be trying to pull the package from a different location. Why is that?
![image](https://user-images.githubusercontent.com/66448475/91922232-4d990900-ec82-11ea-9329-1baff8888fbf.png)

**Comment by lecy** [comment]
R gets installed in your root program directory, which usually lives at C:// on a most window machines. 

R packages are a bit trickier because they need to unzip files and move them into the proper folders, then change "pointers" and other settings in Windows so that executive (program launch files) can be activated. 

Most computers have firewalls built around the C:// directory so that you don't have viruses randomly adding files to core program directories, so some packages trigger too many conflicts to install in the root folders. A separate local R user library is created, usually in your Documents folder. 

It looks like the Rcpp package might have gotten corrupted or deleted during install (this happens often if a package is running in the background of R Studio and you try to install new packages - some files are locked when active, so the new install tried to delete the old install and it misses a file, then the package stops working). Another student had a similar issue because her local library was inside of DropBox, which kept locking files to sync them and thus causing problems during install. 

I would recommend closing R Studio and opening a basic R shell - this can minimize conflicts from packages R Studio might be running in the background. 

Try installing **Rcpp** before re-installing **geojsonio**.

Last line of defense is to go into your local R library and manually delete the folders for the conflicted packages and start over. 

These conflicts are never fun, but it takes 3 minutes to fix once you know the tricks. 

Some of these packages require dozens of other packages to operate, so there are lots of dependencies. Each package is written by different coders and maintained by volunteers. There is no product team that tests packages on three dozen operating systems and resolves conflicts for you. So these issues are the admissions fee you pay to get into the open source disco party :-)

**Comment by ekmcintyre** [comment]
I installed Rcpp and re-installed geojsonio in my basic R shell and was able to locate the packages on my computer as well. I deleted my old lab files and re-downloaded the template, tried to run the `Load required libraries` chunk and still had the issue with geojsonio. Is the conflicting file the one that keeps popping up in the error message (C:/Users/ekmci/Documents/R/win-library/4.0/Rcpp/libs/x64/Rcpp.dll)? I just have to delete that one and then the one I installed on the basic R shell should function in RStudio okay?

**Comment by lecy** [comment]
This is a helpful thread: 

https://github.com/RcppCore/Rcpp/issues/1095

**Comment by lecy** [comment]
Which version of R are you running ? 

4.0.0 was a big new release, so it had some bugs that have been fixed in 4.0.1 and 4.0.2. 

```r
An easy solution is to update R if you don't have a reason to persist in using R 4.0.0 for Windows.
I confirmed the error occurred on R 4.0.0 for Windows.
However, the error didn't occur on R 4.0.1 for Windows and R 4.0.2 for Windows.
```

**Comment by ekmcintyre** [comment]
I am installing 4.0.2 right now. I had 4.0.0. After it installs do I need to delete the older version?

**Comment by lecy** [comment]
No, R Studio will use the most recent version. But I would just to keep your computer uncluttered and not use the old one on accident. 

I keep old versions only because sometimes old packages that are not being maintained might not run on the new version. None of the packages we use here would have that problem, though. 

You will have to re-install some packages, but it hopefully that will do the trick!

**Comment by ekmcintyre** [comment]
I just tested loading the packages on a new .rmd file
![image](https://user-images.githubusercontent.com/66448475/91939744-328ebf00-ecab-11ea-95dd-91da60fa3add.png)
Does that mean it's still not working? Do I have to redo the Rcpp and geojsonio installs on 4.0.2?

**Comment by ekmcintyre** [comment]
Looks like it worked! No error messages as I run the code chunks
![image](https://user-images.githubusercontent.com/66448475/91941456-1c363280-ecae-11ea-914c-f8fd4fd55dde.png)

**Comment by jamisoncrawford** [comment]
Thanks so much @lecy for helping out with this!

@ekmcintyre - glad this is working for you! When you asked, following your screenshot:

> Does that mean it's still not working? Do I have to redo the Rcpp and geojsonio installs on 4.0.2?

... I just wanted to comment that red font, depending on your RStudio settings, doesn't always indicate an error.  R wants you to know what's going on at all times and is often very verbose when doing so.  Red can indicate an error, but it can also indicate a warning that R is doing something that you may not have expected, or it's providing some important details to read.  Try to parse out red messages R sends - you should be able to pick out words like `error` or `failed` that indicate that whatever you tried to do did not work.  

It looks like your message in red just gives details about the package installation/load, it's relationship with other packages, (e.g. "masking" or "overriding" certain functions), and it even tells you at the very end that you can disable warnings - a good indication that it's just a warning, not an error!
